- id: '1588501846352'
  alias: when quiet room fridge door open send notification
  description: ''
  trigger:
  - device_id: a5ea6ad6759345c698658afb9c644309
    domain: binary_sensor
    entity_id: binary_sensor.0x00158d000451d897_contact
    for:
      hours: 0
      minutes: 5
      seconds: 0
    platform: device
    type: opened
  - device_id: 70146a3c3a6247d59063afbfeea3eb7f
    domain: binary_sensor
    entity_id: binary_sensor.0x00158d00049fb09a_contact
    for:
      hours: 0
      minutes: 5
      seconds: 0
    platform: device
    type: opened
  condition: []
  action:
  - data:
      message: Olly left the fridge open.
    service: notify.telegram
- id: '1591583687656'
  alias: every thursday at 7:30am, turn off alarm auto arm
  description: ''
  trigger:
  - at: 07:30
    platform: time
  condition:
  - condition: time
    weekday:
    - thu
  action:
  - data: {}
    entity_id: input_boolean.alarm_auto_arm_schedule
    service: input_boolean.turn_off
- id: '1591583801235'
  alias: every thursday at 12pm, turn on alarm auto arm
  description: ''
  trigger:
  - at: '12:00'
    platform: time
  condition:
  - condition: time
    weekday:
    - thu
  action:
  - data: {}
    entity_id: input_boolean.alarm_auto_arm_schedule
    service: input_boolean.turn_on
