default_config:
homeassistant:
  name: 313A
  latitude: -33.990236
  longitude: 151.090537
  elevation: 20
  unit_system: metric
  time_zone: Australia/Sydney
  whitelist_external_dirs:
    - "/tmp/homekit"
  packages: !include_dir_named integrations

group: !include_dir_merge_named groups/
automation: !include automations.yaml
