- id: '1603065400361'
  alias: 'bedroom lights: when dimmer ch2 change, toggle bedsides'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.bedroom_dimmer_switch_2
    to: 'on'
    from: 'off'
  - platform: state
    entity_id: binary_sensor.bedroom_dimmer_switch_2
    to: 'off'
    from: 'on'
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: light.bedroom_lamps
        state: 'on'
      sequence:
      - service: light.turn_off
        data: {}
        entity_id: light.bedroom_lamps
    default:
    - service: light.turn_on
      data: {}
      entity_id: light.bedroom_lamps
  mode: queued
  max: 10
