- id: '1600953878712'
  alias: New Automation
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.bedroom_button_click
    to: single
  condition: []
  action:
  - type: turn_on
    device_id: 4e5b2bf15a3c477d8481ce60a6bc4eaf
    entity_id: switch.bedroom_kates_bedside
    domain: switch
  - type: turn_on
    device_id: 559a804940fc4f9ea2eb1d21e78877d4
    entity_id: light.bedroom_nicks_bedside
    domain: light
  mode: single
