- id: '1584942961350'
  alias: when fiddle leaf moisture is low, send a notification
  description: ''
  trigger:
  - below: '25'
    entity_id: sensor.soil_moisture_level
    for: '3:00:00'
    platform: numeric_state
  condition: []
  action:
  - data:
      data:
        apns_headers:
          apns-collapse-id: fiddle-leaf-moisture-low
        push:
          thread-id: fiddle-leaf-moisture-low
      message: I'm running dry over here! Give me a drink
      title: Fiddle Leaf Fig
    service: notify.everyone
