# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.2.0/24
        - fd00::/8
  packages: !include_dir_named integrations

automation: !include automations.yaml
script: !include scripts.yaml
logger:
  default: info
  logs:
    samsungwsctl: debug
    custom_components.samsungwsctl: debug
    homeassistant.components.http.ban: warning
