language: python

python:
  - "3.8"

jobs:
  include:
    - stage: test
      name: '[ha] check config: 313a'
      script:
        ./home-assistant/tools/test_config.sh 313a
    - stage: test
      name: '[ha] check config: martin-pl'
      script:
        ./home-assistant/tools/test_config.sh martin-pl
    - stage: test
      name: '[ha] lint and test appdaemon: 313a'
      install:
        - pipenv install --system --dev
      script:
        - cd ./home-assistant/313a/appdaemon
        - black --check .
        - flake8
        - pytest
