sensor:
  platform: template
  sensors:
    kitchen_fridge_power:
      friendly_name: Kitchen Fridge Power
      unit_of_measurement: Watts
      value_template: "{{ state_attr('switch.kitchen_fridge', 'current_power_w') }}"
    kitchen_fridge_current:
      friendly_name: Kitchen Fridge Current
      unit_of_measurement: Amps
      value_template: "{{ state_attr('switch.kitchen_fridge', 'current_a') }}"
    kitchen_fridge_voltage:
      friendly_name: Kitchen Fridge Voltage
      unit_of_measurement: Volts
      value_template: "{{ state_attr('switch.kitchen_fridge', 'voltage') }}"
    kitchen_fridge_today_energy:
      friendly_name: Kitchen Fridge Today Energy
      unit_of_measurement: kWh
      value_template: "{{ state_attr('switch.kitchen_fridge', 'today_energy_kwh') }}"
