homeassistant:
  customize:
    media_player.samsung_smart_tv:
      device_class: tv

media_player:
  - platform: samsungwsctl
    host: 192.168.2.20
    port: 8002
    secure: true
    mac: !secret samsung_smart_tv_mac
    name: "Samsung Smart TV"
