homeassistant:
  customize:
    media_player.samsung_smart_tv:
      device_class: tv

media_player:
  - platform: samsungwsctl
    host: 192.168.2.20
    port: 8002
    secure: true
    mac: !secret samsung_smart_tv_mac
    name: "Samsung Smart TV"

sensor:
  - platform: template
    sensors:
      samsung_smart_tv_source:
        friendly_name: "Samsung Smart TV Source"
        value_template: >-
          {{ state_attr('media_player.samsung_smart_tv','source') }}
