- platform: ffmpeg
  input: !secret hik_303_input
  name: No. 303
- platform: ffmpeg
  input: !secret hik_313a_input
  name: No. 313a
- platform: ffmpeg
  input: !secret hik_top_driveway_input
  name: Top Driveway
- platform: ffmpeg
  input: !secret hik_garage_input
  name: Garage
- platform: ffmpeg
  input: !secret hik_front_door_input
  name: Front Door
- platform: ffmpeg
  input: !secret hik_north_side_input
  name: North Side
- platform: ffmpeg
  input: !secret hik_back_door_input
  name: Back Door
- platform: ffmpeg
  input: !secret hik_pool_input
  name: Pool
- platform: ffmpeg
  input: !secret hik_sideway_west_input
  name: Sideway West
- platform: ffmpeg
  input: !secret hik_sideway_east_input
  name: Sideway East

