- platform: polling
  api_key: !secret telegram_api_key
  allowed_chat_ids:
    - !secret telegram_chat_id
    - 418759991 # Nick
    - 678616261 # Peter
    - 642226869 # Joe
    - 776783100 # Louise
