homeassistant:
  customize:
    cover.blindkit_group_kitchen_front:
      friendly_name: Kitchen Front
      assumed_state: true
    cover.blindkit_group_kitchen_rear:
      friendly_name: Kitchen Rear
      assumed_state: true
    cover.blindkit_group_upstairs:
      friendly_name: Upstairs
      assumed_state: true
    cover.blindkit_group_quiet_room:
      friendly_name: Quiet Room
      assumed_state: true

cover:
- platform: group
  name: blindkit_group_kitchen_front
  entities:
    - cover.blindkit_front_1_left
    - cover.blindkit_front_2_door_left
    - cover.blindkit_front_3_door_right
    - cover.blindkit_front_4_right

- platform: group
  name: blindkit_group_kitchen_rear
  entities:
    - cover.blindkit_back_left
    - cover.blindkit_back_right

- platform: group
  name: blindkit_group_upstairs
  entities:
    - cover.blindkit_nicks_front
    - cover.blindkit_nicks_side
    - cover.blindkit_upstairs_hall_blockout
    - cover.blindkit_upstairs_hall_translucent
    - cover.blindkit_charlotte_side
    - cover.blindkit_oly_side
    - cover.blindkit_oly_back
    - cover.blindkit_joe_back
    - cover.blindkit_master_front_left
    - cover.blindkit_master_front_right

- platform: group
  name: blindkit_group_nicks_blinds
  entities:
    - cover.blindkit_nicks_front
    - cover.blindkit_nicks_side

- platform: group
  name: blindkit_group_quiet_room
  entities:
    - cover.blindkit_quiet_room_left_wall_1
    - cover.blindkit_quiet_room_left_wall_2
    - cover.blindkit_quiet_room_main_blockout
    - cover.blindkit_quiet_room_main_translucent
