homeassistant:
  customize:
    sensor.efergy_731181:
      friendly_name: Solar Input
      icon: mdi:arrow-left
    sensor.efergy_784242:
      friendly_name: Phase B Load
      icon: mdi:power
    sensor.efergy_786148:
      friendly_name: Phase A/C Load
      icon: mdi:power
    sensor.energy_consumed:
      friendly_name: Energy Consumed Today
      icon: mdi:power
    sensor.perdevice_usage:
      hidden: true
    sensor.mains_output:
      icon: mdi:arrow-right
    sensor.mains_input:
      icon: mdi:arrow-left
    sensor.current_load:
      icon: mdi:power

sensor:
  - platform: efergy
    app_token: !secret efergy_app_token
    utc_offset: -600 # 660 for DST.
    monitored_variables:
      - type: amount
        period: day
      - type: current_values

  - platform: template
    # efergy_784242: Phase B Load
    # efergy_786148: Phase AC Load
    # efergy_731181: Solar Input
    sensors:
      mains_input:
        friendly_name: "Mains Input"
        unit_of_measurement: 'W'
        value_template: |
          {% if states.sensor.efergy_784242.state|float > states.sensor.efergy_731181.state|float %}
            {{ states.sensor.efergy_786148.state|float + states.sensor.efergy_784242.state|float - states.sensor.efergy_731181.state|float }}
          {% else %}
            {{ states.sensor.efergy_786148.state|float }}
          {% endif %}

      mains_output:
        friendly_name: "Mains Output"
        unit_of_measurement: 'W'
        value_template: |
          {% if states.sensor.efergy_784242.state|float > states.sensor.efergy_731181.state|float %}
            0
          {% else %}
            {{ states.sensor.efergy_731181.state|float - states.sensor.efergy_784242.state|float }}
          {% endif %}

      current_load:
        friendly_name: Current Load
        unit_of_measurement: 'W'
        value_template: |
          {{ states("sensor.efergy_784242") | float +  states("sensor.efergy_786148") | float }}
