sensor:
  - name: Outdoor Temperature
    platform: mqtt
    device_class: temperature
    state_topic: outdoor_thermometer/temperature
    unit_of_measurement: °C
    availability_topic: outdoor_thermometer/status
    payload_available: 1
    payload_not_available: 0

  - name: Outdoor Humidity
    platform: mqtt
    device_class: humidity
    state_topic: outdoor_thermometer/humidity
    unit_of_measurement: '%'
    availability_topic: outdoor_thermometer/status
    payload_available: 1
    payload_not_available: 0
