version: "2.2"
services:
    mosquitto:
        restart: always
        container_name: mosquitto
        image: eclipse-mosquitto:1.6.4
        volumes:
            - "/etc/homekit/production/mosquitto:/mosquitto/config"
            - "/var/lib/mosquitto:/mosquitto/data"
        ports:
            - "0.0.0.0:1883:1883"
            - "0.0.0.0:9001:9001"
