alarm_control_panel:
  - platform: manual
    delay_time: 120

ios:
  push:
    categories:
      - name: Alarm
        identifier: alarm
        actions:
          - identifier: 'DISARM_ALARM'
            title: 'Disarm'
            activationMode: 'background'
            authenticationRequired: true
            destructive: true
            behavior: 'default'

automation:
  - id: '1601034054491'
    alias: 'alarm: trigger when door opened whilst armed'
    description: ''
    trigger:
    - type: opened
      platform: device
      device_id: e824e2b2a4ff4dea9b16fd7f6234dfc1
      entity_id: binary_sensor.balcony_door
      domain: binary_sensor
    - type: opened
      platform: device
      device_id: 9ae0e5e12ca74203a75203b1c9fbd57b
      entity_id: binary_sensor.front_door
      domain: binary_sensor
    - type: opened
      platform: device
      device_id: 6ebac700fde711eabf1a89a94693ffa5
      entity_id: binary_sensor.laundry_door
      domain: binary_sensor
    condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: alarm_control_panel.ha_alarm
        state: armed_away
      - condition: state
        entity_id: alarm_control_panel.ha_alarm
        state: armed_night
    action:
    - service: alarm_control_panel.alarm_trigger
      data: {}
      entity_id: alarm_control_panel.ha_alarm
    mode: single

  - id: '1601034054491'
    alias: 'alarm: trigger when motion detected whilst armed_away'
    description: ''
    trigger:
    - type: motion
      platform: device
      device_id: 42d8cbc5f64e490c996b0dd2d70c8681
      entity_id: binary_sensor.living_room_motion_occupancy
      domain: binary_sensor
    condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_away
    action:
    - service: alarm_control_panel.alarm_trigger
      data: {}
      entity_id: alarm_control_panel.ha_alarm
    mode: single

  - id: '1601034697138'
    alias: 'alarm: send notification when triggered'
    description: ''
    trigger:
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
      to: triggered
    condition: []
    action:
    - service: notify.mobile_app_nicks_iphone
      data:
        title: Alarm Triggered
        message: The alarm was triggered at {{ now().strftime('%I:%M %p') }}
        data:
          push:
            thread-id: alarm-status
            category: alarm
            sound:
              name: default
              critical: 1
    mode: single

  - id: '1601035010807'
    alias: 'alarm: send notification on disarm if triggered or pending'
    description: ''
    trigger:
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
      to: disarmed
    condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: alarm_control_panel.ha_alarm
        state: pending
      - condition: state
        entity_id: alarm_control_panel.ha_alarm
        state: triggered
    action:
    - service: notify.mobile_app_nicks_iphone
      data:
        title: Alarm Disarmed
        message: The alarm was disarmed at {{ now().strftime('%I:%M %p') }}
        data:
          apns_headers:
            apns-collapse-id: alarm-status
          push:
            thread-id: alarm-status
    mode: single

  - id: '1601035037271'
    alias: 'alarm: send notification when pending'
    description: ''
    trigger:
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
      to: pending
    condition: []
    action:
    - service: notify.mobile_app_nicks_iphone
      data:
        title: Alarm Pending
        message: The alarm was pending at {{ now().strftime('%I:%M %p') }}
        data:
          apns_headers:
            apns-collapse-id: alarm-status
          push:
            thread-id: alarm-status
            category: alarm
    mode: single

  - id: '1601035065291'
    alias: 'alarm: send notification when armed'
    description: ''
    trigger:
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
      to: armed_away
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
      to: armed_night
    condition: []
    action:
    - service: notify.mobile_app_nicks_iphone
      data:
        title: Alarm Armed
        message: The alarm was armed at {{ now().strftime('%I:%M %p') }}
        data:
          apns_headers:
            apns-collapse-id: alarm-status
          push:
            category: alarm
            thread-id: alarm-status
    mode: single

  - id: '1601035419737'
    alias: 'alarm: disarm when everyone arrives home and armed/triggered/pending'
    description: ''
    trigger:
    - platform: state
      entity_id: group.all_people
      to: home
    condition:
    - condition: not
      conditions:
      - condition: state
        entity_id: alarm_control_panel.ha_alarm
        state: armed_night
    action:
    - service: alarm_control_panel.alarm_disarm
      data: {}
      entity_id: alarm_control_panel.ha_alarm
    mode: single

  - id: '1601035712824'
    alias: 'alarm: arm_away when everyone leaves home and disarmed'
    description: ''
    trigger:
    - platform: state
      entity_id: group.all_people
      to: not_home
    condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: disarmed
    action:
    - service: alarm_control_panel.alarm_arm_away
      data: {}
      entity_id: alarm_control_panel.ha_alarm
    mode: single

  - id: '1601036735034'
    alias: 'alarm: disarm when mobile app disarm action fired'
    description: ''
    trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: DISARM_ALARM
    condition: []
    action:
    - service: alarm_control_panel.alarm_disarm
      data: {}
      entity_id: alarm_control_panel.ha_alarm
    mode: single
