homeassistant:
  customize:
    person.nick_whyte:
      entity_picture: "/local/nick.jpg"
    person.kate_scott:
      entity_picture: "/local/kate.jpg"

device_tracker:
  - platform: luci
    host: 192.168.2.1
    username: root
    password: !secret route_password
    new_device_defaults:
      track_new_devices: false

group:
  all_people:
    entities:
      - person.nick_whyte
      - person.kate_scott
