
input_boolean:
  zigbee_permit_join:
    name: Allow devices to join
    initial: off
    icon: mdi:cellphone-wireless

timer:
  zigbee_permit_join:
    name: Time remaining
    duration: 120 # Updated this to the number of seconds you wish

sensor:
  - platform: mqtt
    name: Bridge state
    state_topic: "zigbee2mqtt/bridge/state"
    icon: mdi:router-wireless
  - platform: mqtt
    name: Zigbee2mqtt Networkmap
    # if you change base_topic of Zigbee2mqtt, change state_topic accordingly
    state_topic: zigbee2mqtt/bridge/networkmap/raw
    value_template: >-
      {{ now().strftime('%Y-%m-%d %H:%M:%S') }}
    # again, if you change base_topic of Zigbee2mqtt, change json_attributes_topic accordingly
    json_attributes_topic: zigbee2mqtt/bridge/networkmap/raw

input_text:
  old_friendly_name:
    name: Old Friendly Name
    initial: ''
  new_friendly_name:
    name: New Friendly Name
    initial: ''

automation:
  - id: enable_zigbee_join
    alias: Enable Zigbee joining
    trigger:
      platform: state
      entity_id: input_boolean.zigbee_permit_join
      to: 'on'
    action:
    - service: mqtt.publish
      data:
        topic: zigbee2mqtt/bridge/config/permit_join
        payload: 'true'
    - service: timer.start
      data:
        entity_id: timer.zigbee_permit_join
  - id: disable_zigbee_join
    alias: Disable Zigbee joining
    trigger:
    - entity_id: input_boolean.zigbee_permit_join
      platform: state
      to: 'off'
    action:
    - data:
        payload: 'false'
        topic: zigbee2mqtt/bridge/config/permit_join
      service: mqtt.publish
    - data:
        entity_id: timer.zigbee_permit_join
      service: timer.cancel
  - id: disable_zigbee_join_timer
    alias: Disable Zigbee joining by timer
    trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.zigbee_permit_join
    action:
    - service: mqtt.publish
      data:
        topic: zigbee2mqtt/bridge/config/permit_join
        payload: 'false'
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.zigbee_permit_join

script:
  reconfigure_zigbee_device:
    sequence:
      - condition: template
        value_template: "{{ states('input_text.old_friendly_name') != '' }}"
      - service: mqtt.publish
        data:
          topic: zigbee2mqtt/bridge/config/reconfigure
          payload: "{{ states('input_text.old_friendly_name') }}"
  remove_zigbee_device:
    sequence:
      - condition: template
        value_template: "{{ states('input_text.old_friendly_name') != '' }}"
      - service: mqtt.publish
        data:
          topic: zigbee2mqtt/bridge/config/remove
          payload: "{{ states('input_text.old_friendly_name') }}"
  rename_zigbee_device:
    sequence:
      - condition: template
        value_template: "{{ states('input_text.new_friendly_name') != '' }}"
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ states('input_text.old_friendly_name') == '' }}"
            sequence:
              - service: mqtt.publish
                data:
                  topic: zigbee2mqtt/bridge/config/rename_last
                  payload: "{{ states('input_text.new_friendly_name') }}"
        default:
          - service: mqtt.publish
            data:
              topic: zigbee2mqtt/bridge/config/rename
              payload: >-
                {
                  "old": "{{ states('input_text.old_friendly_name') }}",
                  "new": "{{ states('input_text.new_friendly_name') }}"
                }
