homeassistant:
  customize:
    weather.bom_sydney_airport:
      friendly_name: Weather
    sensor.bom_sydney_airport_air_temp_c:
      icon: mdi:thermometer
      friendly_name: Temperature
    sensor.bom_sydney_airport_feels_like_c:
      icon: mdi:thermometer
      friendly_name: Feels Like
    sensor.bom_sydney_airport_rain_today:
      icon: mdi:water
      friendly_name: Rain Today
    sensor.bom_sydney_airport_weather:
      icon: mdi:waves
      friendly_name: Weather

sensor:
  - platform: bom
    station: IDN60901.94767
    name: Sydney Airport
    monitored_conditions:
      - rain_trace
      - weather
      - apparent_t
      - air_temp

weather:
  - platform: bom
    station: IDN60901.94767
    name: Sydney Airport
