esphome:
  name: fiddleleaf
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: adc
    pin: A0
    unit_of_measurement: "%"
    accuracy_decimals: 0
    icon: "mdi:flower-outline"
    filters:
      - lambda: |-
          if (x > 0.64) {
            return 0;
          } else if (x < 0.32) {
            return 100;
          } else {
            return (0.64-x) / (0.64-0.32) * 100.0;
          }
      - sliding_window_moving_average:
          window_size: 15
          send_every: 15
    name: "Soil Moisture Level"
    update_interval: 20s
  - platform: uptime
    name: Uptime Sensor