esphome:
  name: ledstrip
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
api:
ota:

output:
  - platform: esp8266_pwm
    pin: 5
    id: 'color_red'
  - platform: esp8266_pwm
    pin: 12
    id: 'color_green'
  - platform: esp8266_pwm
    pin: 13
    id: 'color_blue'

light:
  - platform: rgb
    name: "LED Strip"
    red: color_red
    green: color_green
    blue: color_blue
