esphome:
  name: washing_machine
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

i2c:
  sda: GPIO1
  scl: GPIO3
  scan: True
  id: bus_a

sensor:
  - platform: mpu6050
    address: 0x68
    gyro_x:
      name: "Washing Machine Gyro X"
      id: gyro_x
      filters:
        - offset: -18.8
        - lambda: return abs(x);
        - sliding_window_moving_average:
            window_size: 15
            send_every: 5
    gyro_y:
      name: "Washing Machine Gyro Y"
      id: gyro_y
      filters:
        - offset: -0.9
        - lambda: return abs(x);
        - sliding_window_moving_average:
            window_size: 15
            send_every: 5
    temperature:
      name: "Laundry Temperature"
    update_interval: 5s

binary_sensor:
  - platform: template
    device_class: power
    name: "Washing Machine"
    lambda: |-
      if (id(gyro_y).state +  id(gyro_x).state > 1) {
        return true;
      } else {
        return false;
      }
    filters:
      - delayed_off: 15min
      - delayed_on: 2min
  - platform: template
    device_class: vibration
    name: "Washing Machine Vibration Detected"
    lambda: |-
      if (id(gyro_y).state +  id(gyro_x).state > 1) {
        return true;
      } else {
        return false;
      }
